// <auto-generated />
using System;
using HNW.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HNW.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330194250_SeedNetworkReferenceLinks")]
    partial class SeedNetworkReferenceLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HNW.Data.Models.NetworkTestDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("varchar(253)");

                    b.Property<string>("ExpectedStatus")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PolicyPrUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PolicyStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Port")
                        .HasColumnType("int");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("NetworkTestDefinitions");
                });

            modelBuilder.Entity("HNW.Data.Models.NetworkTestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<Guid>("NetworkTestDefinitionId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("NetworkTestDefinitionId");

                    b.ToTable("NetworkTestResults");
                });

            modelBuilder.Entity("HNW.Data.Models.NetworkTestStateChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("NetworkTestDefinitionId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("NewState")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<bool>("OldState")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("NetworkTestDefinitionId");

                    b.ToTable("NetworkTestStateChanges");
                });

            modelBuilder.Entity("HNW.Data.Models.ReferenceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnvironmentRelative")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("ReferenceLinks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Category = "OpenShiftNetworking",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "How the OpenShift SDN plugin manages pod networking and inter-namespace isolation.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 10,
                            Title = "OpenShift SDN Overview",
                            Url = "https://docs.openshift.com/container-platform/4.14/networking/openshift_sdn/about-openshift-sdn.html"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Category = "OpenShiftNetworking",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Overview of Kubernetes NetworkPolicy and how OpenShift enforces default-deny.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 20,
                            Title = "Network Policy in OpenShift",
                            Url = "https://docs.openshift.com/container-platform/4.14/networking/network_policy/about-network-policy.html"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Category = "OpenShiftNetworking",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Step-by-step guide to creating NetworkPolicy objects for egress traffic.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 30,
                            Title = "Configuring egress NetworkPolicy",
                            Url = "https://docs.openshift.com/container-platform/4.14/networking/network_policy/creating-network-policy.html"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Category = "OpenShiftNetworking",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Platform-specific NetworkPolicy guidance for BC Gov OpenShift namespaces.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 40,
                            Title = "BC Gov Private Cloud — Network Policies",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/openshift-projects-and-access/network-policies/"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            Category = "OpenShiftNetworking",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "OVN-Kubernetes network provider used in newer OpenShift clusters including Emerald.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 50,
                            Title = "OVN-Kubernetes Overview",
                            Url = "https://docs.openshift.com/container-platform/4.14/networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.html"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            Category = "ClusterTiers",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Comparison of Silver, Gold, and Emerald cluster capabilities, SDN implementations, and networking differences.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 10,
                            Title = "BC Gov Private Cloud Clusters",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/platform-architecture-reference/openshift-clusters"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            Category = "ClusterTiers",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Silver-specific networking: OpenShift SDN, HAProxy router, ingress/egress defaults.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 20,
                            Title = "Silver Cluster Networking Notes",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/platform-architecture-reference/openshift-clusters#silver"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            Category = "ClusterTiers",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Gold-specific networking: OVN-Kubernetes, default-deny stance, multi-zone topology.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 30,
                            Title = "Gold Cluster Networking Notes",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/platform-architecture-reference/openshift-clusters#gold"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            Category = "ClusterTiers",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Emerald-specific networking: strict default-deny ingress AND egress, AVI load balancer, DataClass enforcement.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 40,
                            Title = "Emerald Cluster Networking Notes",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/platform-architecture-reference/openshift-clusters#emerald"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            Category = "ClusterTiers",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "AVI replaces HAProxy on Emerald. Routes must carry the correct AVI InfraSettings annotation.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 50,
                            Title = "AVI / NSX Advanced Load Balancer (Emerald)",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/platform-architecture-reference/openshift-clusters#avi-nsx-advanced-load-balancer"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            Category = "DataClassAndZones",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "How BC Government classifies data (Low / Medium / High) and what each class means for network access.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 10,
                            Title = "BC Gov DataClass Overview",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/platform-architecture-reference/network-zones-and-data-classification"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            Category = "DataClassAndZones",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "The three network zones and which data classes are permitted in each.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 20,
                            Title = "Network Zone Model (Public / Private / Restricted)",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/platform-architecture-reference/network-zones-and-data-classification#network-zones"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            Category = "DataClassAndZones",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Required pod label DataClass: Medium and how it interacts with Emerald's AVI InfraSettings.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 30,
                            Title = "DataClass Labels on Pods and Routes",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/platform-architecture-reference/network-zones-and-data-classification#labels"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            Category = "DataClassAndZones",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "How DataClass labelling determines which egress network zones your pods can reach on Emerald.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 40,
                            Title = "Impact of DataClass on Egress (Emerald)",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/platform-architecture-reference/network-zones-and-data-classification#emerald-impact"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333305"),
                            Category = "DataClassAndZones",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Only dataclass-medium has a registered VIP on Emerald. Never use dataclass-low.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 50,
                            Title = "AVI InfraSettings — dataclass-medium vs dataclass-low",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/platform-architecture-reference/avi-infrasettings"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            Category = "NetworkPolicyPatterns",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Every network flow requires TWO policies: ingress on the receiver AND egress on the sender.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 10,
                            Title = "Two-policy rule: ingress + egress",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/openshift-projects-and-access/network-policies/#two-policy-rule"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444402"),
                            Category = "NetworkPolicyPatterns",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "All pods need an explicit DNS egress policy (UDP 53 + TCP 53) on Emerald — not included by default.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 20,
                            Title = "DNS egress policy (UDP+TCP 53)",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/openshift-projects-and-access/network-policies/#dns"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444403"),
                            Category = "NetworkPolicyPatterns",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "How to write a CIDR-based egress policy to allow traffic to external systems or on-prem networks.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 30,
                            Title = "Allow egress to external IP / CIDR",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/openshift-projects-and-access/network-policies/#egress-cidr"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444404"),
                            Category = "NetworkPolicyPatterns",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kubernetes reference: only open the specific port and protocol needed — never wildcard egress.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 40,
                            Title = "Least-privilege NetworkPolicy",
                            Url = "https://kubernetes.io/docs/concepts/services-networking/network-policies/#the-networkpolicy-resource"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444405"),
                            Category = "NetworkPolicyPatterns",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Standard database and service ports used when writing egress NetworkPolicy rules.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 50,
                            Title = "Common port reference (Oracle 1521, MSSQL 1433, PG 5432, MySQL 3306)",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/openshift-projects-and-access/network-policies/#common-ports"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555501"),
                            Category = "SdnGuidance",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Emerald enforces default-deny on BOTH ingress and egress. Every flow must be explicitly allowed.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 10,
                            Title = "Default-deny ingress and egress on Emerald",
                            Url = "https://developer.gov.bc.ca/docs/default/component/platform-developer-docs/docs/platform-architecture-reference/openshift-clusters#default-deny"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555502"),
                            Category = "SdnGuidance",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Guidance on SDN migration and the differences between OpenShift SDN, Calico, and OVN-Kubernetes.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 20,
                            Title = "Calico vs OVN-Kubernetes",
                            Url = "https://docs.openshift.com/container-platform/4.14/networking/ovn_kubernetes_network_provider/migrate-from-openshift-sdn.html"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555503"),
                            Category = "SdnGuidance",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "How to view and inspect NetworkPolicy objects on a running cluster to diagnose connectivity failures.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 30,
                            Title = "Troubleshooting NetworkPolicy",
                            Url = "https://docs.openshift.com/container-platform/4.14/networking/network_policy/viewing-network-policy.html"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555504"),
                            Category = "SdnGuidance",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Use oc debug to launch a temporary pod and test egress connectivity with curl, nc, or nslookup.",
                            IsActive = true,
                            IsEnvironmentRelative = false,
                            SortOrder = 40,
                            Title = "oc debug — testing connectivity from a pod",
                            Url = "https://docs.openshift.com/container-platform/4.14/support/troubleshooting/troubleshooting-network-issues.html"
                        });
                });

            modelBuilder.Entity("HNW.Data.Models.NetworkTestResult", b =>
                {
                    b.HasOne("HNW.Data.Models.NetworkTestDefinition", "NetworkTestDefinition")
                        .WithMany("Results")
                        .HasForeignKey("NetworkTestDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NetworkTestDefinition");
                });

            modelBuilder.Entity("HNW.Data.Models.NetworkTestStateChange", b =>
                {
                    b.HasOne("HNW.Data.Models.NetworkTestDefinition", "NetworkTestDefinition")
                        .WithMany("StateChanges")
                        .HasForeignKey("NetworkTestDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NetworkTestDefinition");
                });

            modelBuilder.Entity("HNW.Data.Models.NetworkTestDefinition", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("StateChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
